- name: catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name : Setup NPM source #refere RoboShop-Documentation
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash" #execute until this part
