- name: web component
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove html directory
    #we have 2 options for removing: 1. Remove Directory & Create again. 2. Remove Files From html Directory & Reload again
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent #absent means remove

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory

  - name: download web artifact #frontend content
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: unzip or unarchive web.zip
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy roboshop.conf
    # as we created roboshop.conf with code and localhosts ip we have to give for catalogue,user,cart,shipping,payment
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf 

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted

